
title: AbhijitL
email: labhijitsingh13@gmal.com
description: >- # this means to ignore newlines until "baseurl:"
  Official site of Abhijit Leihaorambam
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: leihaorambam
github_username:  AbhijitL

include: ['_pages']

# build settings
permalink: pretty
markdown: kramdown
paginate: 5
paginate_path: "/blog_posts/page:num/"
permalink: "/blog_posts/:title/"

gems:
  - jekyll-feed
  - jekyll-autoprefixer
  
plugins:
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock

sass:
  sass_dir: _sass